[package]
name = "blog"
edition = "2024"

[dependencies]
askama = "0.14.0"
base64 = "0.22.1"
glob = "0.3.3"
highlight = { git = "https://github.com/noClaps/znak" }
jiff = { version = "0.2.15", default-features = false, features = [
  "perf-inline",
] }
lol_html = "2.7.0"
tree-sitter-languages = { git = "https://github.com/noClaps/znak", version = "0.0.0", features = ["bash", "c", "html", "json", "python", "typescript"] }
znak = { git = "https://github.com/noClaps/znak" }
